### ISSUE TITLE
Rework handle id site

### ISSUE THREAD

**Issue by bretterer** [stormpath/stormpath-sdk-php#110]
In the handle method, we are assuming sub will always contain a valid account.  This causes an issue if the account is logged out and a handle of id site happens.  Possibly make account null, and if sub is there, then set it to account.

https://github.com/stormpath/stormpath-sdk-php/blob/dev/src/Resource/Application.php#L410-L419

**Comment by epenet** [comment]
I'm currently building a simpleSAMLphp plugin based on Stormpath with Site-ID.
On logout, I want to do is make sure that the user is logged off from Stormpath (I don't really care whether he was previously logged in or not) before I redirect the user back to original SP page. The above error prevents me from accessing the $result->state which I need to finalize the logout and redirect correctly.

**Comment by bretterer** [comment]
That makes things a little clearer on what you are doing and expecting.  I will put this into the workflow for a bugfix.

-Brian

**Comment by bretterer** [comment]
@epenet We have made a patch for this issue.  We will be releasing the patch soon.
