### ISSUE TITLE
Get verification token programatically

### ISSUE THREAD

**Issue by nathanjohnson320** [stormpath/stormpath-sdk-php#111]
We're trying to use multiple verification emails for our users and to do that we're probably going to have to use an external email service to send an email based on a segment. But the user is still going to have to visit the page where the "sptoken" variable gets passed.

So my questions is: is there a way to generate an "sptoken" for an email address? This way we can send the token to our email service then the user still clicks the link that calls \Stormpath\Client::verifyEmailToken

**Comment by bretterer** [comment]
@nathanjohnson320:  Which SP Token are you talking about?  Are you talking the token to reset their password, or the token to verify their email address for when they sign up?

**Comment by nathanjohnson320** [comment]
@bretterer the one to verify when they sign up.

**Comment by bretterer** [comment]
@nathanjohnson320 When you create the account and have verification turned on, the email is sent automatically.  You are able to access that token from the account resource, however they will have already received the email.

**Comment by nathanjohnson320** [comment]
@bretterer ok I don't think it's possible to do what I want to do then. I was trying to turn off the verification workflow through stormpath and send the email with the sptoken via another service but that isn't possible.
