### ISSUE TITLE
Upgrade Guzzle 

### ISSUE THREAD

**Issue by bretterer** [stormpath/stormpath-sdk-php#120]
We need to get a new version of guzzle in the SDK ... The current version is causing issues in the Laravel Integration.  See https://github.com/stormpath/stormpath-laravel/issues/17 for more info

**Comment by bretterer** [comment]
Currently we are still supporting PHP5.4 and the max guzzle we could go is 5.3.0  

I would like to do some research into how many api calls we get using PHP 5.4 and see if we can stop supporting it, since PHP5.4 is EOL now.

**Comment by miketheman** [comment]
A recent install shows:
```
guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
```

**Comment by bretterer** [comment]
Thanks @miketheman .  We are aware of the abandoned package notice.  We have the update on our roadmap and will be working on it in the future to rip out Guzzle 3 and implement the newest version of Guzzle.  Please watch this issue for future updates.

**Comment by dkvk** [comment]
@bretterer please consider implement the PSR7-standard when it comes to HTTP-messaging as this would open up for doing extension more easily. I would suggest using http://httplug.io/ to make a clear separation between the client implementation and your SDK. When it comes to Guzzle there is a adapter already in place http://docs.php-http.org/en/latest/clients/guzzle6-adapter.html

**Comment by magnusnordlander** [comment]
Just a small heads up. I was feeling bored tonight, so I started working on this in https://github.com/fervo/stormpath-sdk-php/tree/psr-7

The code itself is pretty much finished, but the tests haven't been updated yet (most do pass without any changes though), and I think there's a couple of refactorings I'd like to do before I open a PR. I expect to send a PR by the end of the week.

**Comment by magnusnordlander** [comment]
There, I've now opened a PR for it, #173.

**Comment by bretterer** [comment]
Merged into dev branch ready for release.
