### ISSUE TITLE
Tests fail when using free developer account

### ISSUE THREAD

**Issue by magnusnordlander** [stormpath/stormpath-sdk-php#131]
When using the free developer accounts, the tests fail. There seems to be multiple causes for this. One is the application limit, which causes failures in tests like CacheTest. Another is the fact that developer accounts do not have SAML.

I certainly realize that you need to have restrictions on free accounts, but would it be possible to set up testing accounts with other severe limitations (such as number of users, or restricting all user emails to example.com or something) allowing registration of accounts for running the test suite?

**Comment by bretterer** [comment]
We will need to tag tests that can not be tested on free accounts.  Thank you @magnusnordlander for pointing this out.
