### ISSUE TITLE
Custom Data Search

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-php#134]
https://stormpath.atlassian.net/wiki/display/AM/Custom+Data+Search

**Comment by tobiassjosten** [comment]
Having looong awaited custom data search, it's a shame being teased by just a link to this protected resource. :)

**Comment by bretterer** [comment]
Hi @tobiassjosten ... Stay tuned to this ticket for updates on where we are in development of Custom Data Search!

-Brian

**Comment by omgitstom** [comment]
This should be supported today for customers attempting to do customData search.

$accounts = $tenants->accounts->setSearch(['customData.key'=>'123']);
foreach($accounts as $account) {
  var_dump($account);  // object(Stormpath\Resource\Account)
}

Brian can you confirm, update docs, and close this issue?

**Comment by bretterer** [comment]
Resolved and ready for production.
