### ISSUE TITLE
Negate search

### ISSUE THREAD

**Issue by tobiassjosten** [stormpath/stormpath-sdk-php#135]
Looking over the matching logic in the documentation and the methods in `Stormpath\Resource\Search` I don't see a way to negate an expression. I want to, for example, fetch all accounts with a username other than *tobiassjosten* – how would I do that?

**Comment by bretterer** [comment]
Hi @tobiassjosten Thank you for your question.  I just wanted to touch base with you here to let you know that I see the question here and will respond soon.

**Comment by bretterer** [comment]
@tobiassjosten I am going to put this as an issue because I dont believe there is a way to do it right now.

**Comment by tobiassjosten** [comment]
@bretterer Good to know, thanks.

**Comment by bretterer** [comment]
@tobiassjosten digging a little deeper on this, this is not a supported feature in the API of Stormpath, so the SDK will not be able to support it.  

I am going to close out this ticket since there is nothing we can do on the SDK side.  I have made a request to our team to look into this further.
