### ISSUE TITLE
Caching for PHP

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-php#16]
Implement Memory, Redis, and Memcached Caching in the PHP SDK

Design can be followed in Node.  The Client accepts caching options, which gets set on the Datastore's CacheHandler.

https://github.com/stormpath/stormpath-sdk-node/blob/master/lib/Client.js

http://docs.stormpath.com/nodejs/api/client
http://docs.stormpath.com/nodejs/api/cache
http://docs.stormpath.com/nodejs/api/cacheManager

**Comment by bretterer** [comment]
I think this can now be closed.
