### ISSUE TITLE
PSR-0 has been deprecated.  All of the PHP SDK is psr-0 and needs to be changed over to PSR-4.  

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-php#17]

**Comment by potherca** [comment]
Is anyone actively working on this or are you waiting for pull-requests?

**Comment by bretterer** [comment]
@potherca We always welcome pull requests.  Feel free to submit one for review.  If you do, please submit it against the dev branch.

**Comment by bretterer** [comment]
Will be implemented in V1.12.0.  See Commit 15aee30

**Comment by potherca** [comment]
Awesome! 🚀
