### ISSUE TITLE
[Discussion] Create a deprecation policy

### ISSUE THREAD

**Issue by magnusnordlander** [stormpath/stormpath-sdk-php#178]
During the work on #173, the issue of deprecation in preparation of a version 2.0 came up. At the time we avoided any decision, which was fine because it was such a tangential issue anyway.

I think that it still merits discussion though, hence this issue.

Given that this library follows semver, no BC breaks are possible in minor versions. However, it's become clear that some facilities in this library could benefit from a BC breaking cleanup. 

I want to discuss under what circumstances you think we can allow BC breaks in a major version (semver says any, but other projects e.g. Symfony says "only code that has been previously marked as deprecated"), and how we would go about marking code as deprecated.

In Symfony (which is what I'm most used to), deprecation warnings are silently triggered, i.e. `@trigger_error(..., E_USER_DEPRECATED);`. I think that makes a lot of sense, because it makes dealing with them optional.

I think it makes sense to allow any BC breaks in a major version, but still encouraging that when possible, emit silent deprecations. Going full monty and requiring deprecation warnings in all cases is nice, but it think that might be prohibitively difficult.

What say you?

**Comment by bretterer** [comment]
When a method is to be deprecated, a warning `SHOULD` be triggered about the deprecation.  This can, of course, be a little bit of an issue in some cases so please follow what the term `SHOULD` means inside of RFC 2119.  

So I guess some guidelines:

1. Package MUST follow guidelines set by semver 
2. Any BC break MUST trigger a major version update
3. Language Version bumps MAY be a major version update but MUST trigger at least a minor version update
4. Any depreciation of public API of package SHOULD trigger a warning stating so”.

**Comment by magnusnordlander** [comment]
Cool, seems reasonable. By "trigger a warning" I take it you mean doing a silent trigger of a E_USER_DEPRECATION (i.e. `@trigger_error(..., E_USER_DEPRECATED);`?

**Comment by bretterer** [comment]
I am guessing it will be something like that.  I don't want to be specific on what to use, as it could potentially change. We will use what is standard at the time.
