### ISSUE TITLE
Guzzle Upgrade...

### ISSUE THREAD

**Issue by iaejean** [stormpath/stormpath-sdk-php#19]
Hello, sorry, I'm trying to use this SDK, and now I'm using "mailgun / mailgu-php", "rackspace / php-OpenCloud" using Guzzle 3.8. * Or 3.9. *, And I would use this SDK composer me because now I require Guzzle mark 3.7. *.

Sorry my bad english.

**Comment by bretterer** [comment]
reference #27

**Comment by omgitstom** [comment]
Fixed in 1.2.1.beta
