### ISSUE TITLE
Needs more cowbell! I mean, stricter code coverage!

### ISSUE THREAD

**Issue by potherca** [stormpath/stormpath-sdk-php#20]
For the code-coverage to be anywhere near useful, instead of the current configuration, PHPUnit 4.* should be used with stricter settings in regards to coverage in the `phpunit.xml.dist` file. 

Also, there should be a `phpunit.xml.dist` file :wink: 

If you feel up for it, I wouldn't mind opening a PR with some suggestions...

**Comment by lhazlewood** [comment]
Hi!

Thanks for these issues - this is great!  And we'd love to see PRs!  We really appreciate contributions!

**Comment by bretterer** [comment]
Hi @potherca!  I submitted a pull request and wanted to see if this is what you were thinking.

https://github.com/stormpath/stormpath-sdk-php/pull/26

**Comment by potherca** [comment]
Looks good! I added some minor suggestions, but this is already pretty sweet! :cake:

**Comment by bretterer** [comment]
This is now planned for 1.9.0.beta

**Comment by bretterer** [comment]
Has been merged into dev ready to be released
