### ISSUE TITLE
Directory Inclusion Error

### ISSUE THREAD

**Issue by asithade** [stormpath/stormpath-sdk-php#30]
I have added the SDK into the directory but I can't get past the initial setup without getting the following error: 

> Warning: include() [function.include]: Failed opening '/nas/wp/www/cluster-1772/wp-content/themes/salient/sp_api/Stormpath/ClientBuilder' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /nas/wp/www/cluster-1772/wp-content/themes/salient/sp_api/Stormpath.php on line 29

> Fatal error: Class 'Stormpath\ClientBuilder' not found in /nas/wp/www/cluster-1772/wp-content/themes/salient/stormpath.php on line 13

Here is my code in the file stormpath.php

```php
require 'sp_api/Stormpath.php';

$apiKeyFile = '.stormpath/apiKey.properties';

$builder = new Stormpath\ClientBuilder();
$client = $builder->setApiKeyFileLocation($apiKeyFile)->build();

$apps = $client->tenant->applications;
$apps->search = array('name' => 'My Application');
$application = $apps->getIterator()->current();
```

I've also had the sp_api called "Stormpath" before as well, thinking there might have been some issue with the directory name.

**Comment by omgitstom** [comment]
Hi @asithade 

I have seen this error before, you mention that this might be an issue with the directory name.  Do you mean the Stormpath Directory resource or the file system directory?

@bretterer @ecrisostomo any thoughts here?

Thanks!
Tom

**Comment by asithade** [comment]
@omgitstom I kept noticing that "salient/sp_api/Stormpath/ClientBuilder" would normally be salient/sp_apiStormpath/ClientBuilder" where it was missing a forward slash until I edited the Stormpath.api from the SDK to add a forward slash on line 29 before $file. 

A note: I was able to have this all working fine by using Composer on a different server, but unfortunately I don't have access to SSH on the production server to use it there, so I'd need to install this manually.

**Comment by asithade** [comment]
@omgitstom -- do you happen to have any update on this?

**Comment by bretterer** [comment]
@asithade, because this is a composer package, and you do not have ssh, you will need to install the full composer packed (after you composer install) into the server.  After that, make sure you include the vendor autoloader file instead of stormpath files directly

**Comment by asithade** [comment]
@bretterer -- is there no manual way to do this that does not require composer? I would think that not every user has SSH access to their servers to do such an install.

**Comment by bretterer** [comment]
Yes and no.  On your local computer, do the composer install then move the
folder to the server

**Comment by asithade** [comment]
That sounds good. Thanks

**Comment by mattdodge** [comment]
I realize we can run composer to build the folder and get this to work, but in my opinion this is still an issue. On the README there is an example cited where composer is not required and it is run from source. However, when you try and include anything I get the same errors that are mentioned in the original issue.

I was able to fix them by changing `Stormpath.php`, mainly I made the autoload function look like this:
```php
function Stormpath_autoload($className) {
    if (substr($className, 0, 9) != 'Stormpath') {
        return false;
    }
    $file = str_replace('\\', '/', $className) . ".php";
    return include dirname(dirname(__FILE__)) . DIRECTORY_SEPARATOR . "$file";
}
```

Would you like me to open a new issue/pull request for this? Or re-open this issue? Or are we convinced it's not a valid concern?

**Comment by bretterer** [comment]
Hey @mattdodge,  I will go ahead and re-open this issue based on your comments.  It is not a suggested way to use our SDK anymore outside of composer as we have dependencies that we need installed via composer.  

The note here should be to remove this autoloader and remove any reference in the README saying you can use this package outside of composer.

**Comment by mattdodge** [comment]
Cool, yeah that sounds good to me. Composer makes things pretty easy and seems pretty standard at this point, but when I saw the docs saying I could build from source I figured I would avoid some overhead and give it a go.
