### ISSUE TITLE
User Agent

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-php#31]
Stormpath needs to send the PHP version

All SDKs and Integrations must report back to stormpath the information about its current running environment.  This will use the User-Agent http header.
The information will be in the following format:

```javascript
stormpath-flask/0.1 flask/0.10 stormpath-sdk-python/1.2.5 python/2.2.3 Windows/8.1 (%ANYTHING_ELSE%)
```

This can be defined as:
+ The stormpath integration and version separated by a '/'.  If there is no integration being used, this can be omitted
+ The stormpath sdk and version separated by a '/'
+ The runtime information (runtime/version)
+ Integration Runtime (if there is no integration being used, this can be omitted)
+ SDK Runtime
+ The OS common name and version separated by a '/'.
+ All other system information included in parentheses

**Comment by ecrisostomo** [comment]
Implemented on version 1.4.0.beta
