### ISSUE TITLE
Remove support for PHP 5.3

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-php#32]
PHP 5.3 was EOL'd 7 months ago.  I do not want Stormpath to manage support for unsupported version of PHP

**Comment by omgitstom** [comment]
https://github.com/stormpath/stormpath-sdk-php/pull/53

**Comment by ecrisostomo** [comment]
@omgitstom I don't think https://github.com/stormpath/stormpath-sdk-php/pull/53 fixes this issue.

**Comment by bretterer** [comment]
@ecrisostomo: In order for us to determine the best time to stop supporting PHP 5.3, we need to have the changes in #53 for a few months to check usage of PHP 5.3 and make sure it is low enough.  So in a way #53 will help us to fix this issue.

**Comment by bretterer** [comment]
This will be removed in 1.9.0.beta   It has been merged into dev branch
