### ISSUE TITLE
ID Site Support for PHP

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-php#33]
@bretterer ping me when you are ready to start on this.  

http://docs.stormpath.com/guides/using-id-site/

**Comment by magnusnordlander** [comment]
Hey, I've implemented ID site support in the [Symfony bundle](https://github.com/rdey/StormpathBundle) I'm writing integrating Stormpath. Feel free to simply snag those classes out of the bundle and move it here :) 

The bundle is MIT licensed, so licensing isn't an issue.

**Comment by bretterer** [comment]
Implemented since 1.3.0-beta
