### ISSUE TITLE
Error when saving Custom Data

### ISSUE THREAD

**Issue by morticue** [stormpath/stormpath-sdk-php#42]
I have encountered an error when I try to save to the Custom Data object of an Account.

This code below works, I can verify the newly saved data in the stormpath gui at https://api.stormpath.com/login . The variable `$account` is an object of class `Stormpath\Resource\Account` .

```
1. $customData = $account->getCustomData();
2. // $customData->foo;
3. $customData->foo = [1, 2];
4. $customData->save();
```

However, if I uncomment line 2. I get an error on line 4 with `code 3003`:

    "Property name 'createdAt' is invalid. Property names may not equal any of the following reserved names: 'href', 'createdAt', 'modifiedAt', meta', 'spMeta', 'spmeta', 'ionmeta', or 'ionMeta'."

It seems there is some kind of bug in the library which sets that createdAt-property if I read from the CustomData object, which prevent saving to it. If I dont read something from it first, it works to save to it.

**Comment by dkvk** [comment]
When reading the first property from the CustomData object, all its properties get materialized. Including the reserved ones like createdAt. You find it here: https://github.com/stormpath/stormpath-sdk-php/blob/master/src/Stormpath/Resource/Resource.php#L63-L83

In other words this problem occurs by current design.

To work around this you could remove the reserved properties from the object before save. Or do all changes before reading to any property.

**Comment by ecrisostomo** [comment]
Fixed on 1.6.0.beta.

**Comment by dadixon** [comment]
I don't think this is resolved. I'm doing the same thing and I get the same error. Is there some better way of doing this?

**Comment by bretterer** [comment]
@dadixon I am going to leave this closed as it seems this may have been an issue of a version you had installed.  if this is not the case, please let me know.

**Comment by tobiassjosten** [comment]
I just bumped into this error and an update (from `1.2.1.beta` to `1.12.0`) solved it for me.

**Comment by bretterer** [comment]
@tobiassjosten Yes, Upgrading to anything past 1.6.0.beta will fix this issue.
