### ISSUE TITLE
Expanded resources and caching

### ISSUE THREAD

**Issue by dkvk** [stormpath/stormpath-sdk-php#48]
When caching expanded resources the key being used is not consistent.

The cache key that is used for cacheing a resource is based on the resource href as well as its options. This is done in https://github.com/stormpath/stormpath-sdk-php/blob/bc64a5d43712cfa3fbc69bd476f16ae66fd495ab/src/Stormpath/Cache/Cacheable.php#L48-L56

The problem when a resource gets updated and saved the key being used to first delete it from the cache is just based on the href: https://github.com/stormpath/stormpath-sdk-php/blob/bc64a5d43712cfa3fbc69bd476f16ae66fd495ab/src/Stormpath/Cache/Cacheable.php#L39
and not with its options.

As example, we always fetch accounts with expansion of its groups. The account data is saved to a cache key as:
1. `https://api.stormpath.com/v1/accounts/7BVwoUmoMCfWdxrHOjtLm4:groups`

Later we update and save changes to the account, the cache key will then be:
2. `https://api.stormpath.com/v1/accounts/7BVwoUmoMCfWdxrHOjtLm4`
which gives a miss as that key does not exist.

Second, the data is saved to the same key:
3. `https://api.stormpath.com/v1/accounts/7BVwoUmoMCfWdxrHOjtLm4`
which then holds the newly updated data.

Later we fetch the same account with expansion of its groups. The key for that will be:
4. `https://api.stormpath.com/v1/accounts/7BVwoUmoMCfWdxrHOjtLm4:groups`
which of course doesn't include the newly updated data, but the data from the 1. fetch.

I would suggest a solution to this to just skip the options our from the key creation. Which would keep the same cache key over the whole lifecycle of the cached item. Also it would work incremental as when ever new data is expanded it would be saved to the cached item (overwritten).

**Comment by magnusnordlander** [comment]
The suggested caching strategy would not work when fetching the same object with different expansions. The only way to solve this is with an hierarchical cache. Since there is little reason for the Stormpath library to implement it's own caching library, I would instead suggest using something like [Stash](http://www.stashphp.com) which already provides a cache hierarchy, and supports all of the backends that the Stormpath library currently does.

**Comment by bretterer** [comment]
@dkvk: thank you for the feedback on this. I have marked this as a bug and will look at a fix for this.
