### ISSUE TITLE
Add Resending an Email Verification to PHP SDK

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-php#52]
http://docs.stormpath.com/rest/product-guide/#application-resend-verify-email

**Comment by bretterer** [comment]
I have started working on this.  The workflow is working but the save is throwing an exception.  Catchable fatal error: Argument 2 passed to Stormpath\Resource\Resource::__construct() must be an instance of stdClass, string given in src/Stormpath/Resource/Resource.php on line 36

**Comment by bretterer** [comment]
Set to release in 1.9.0.beta
