### ISSUE TITLE
API Key Authentication

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-php#58]
https://github.com/stormpath/stormpath-sdk-spec/blob/master/specifications/api_auth.md

**Comment by omgitstom** [comment]
https://github.com/stormpath/stormpath-sdk-java/tree/master/impl/src/main/java/com/stormpath/sdk/impl/authc

**Comment by omgitstom** [comment]
https://docs.stormpath.com/guides/api-key-management/

**Comment by bretterer** [comment]
Released in 1.8.0
