### ISSUE TITLE
Group ID and Group Membership ID Different?

### ISSUE THREAD

**Issue by asithade** [stormpath/stormpath-sdk-php#65]
This is my current way of creating a group and associating a user. 

1: Create Account and get Account Href
```php
$account = curl_post_stormpath('https://api.stormpath.com/v1/applications/xxx/accounts', $account_data_string);
$account_href = $account->href;
```
2: Create Group and get Group Href
```php
$res = curl_post_stormpath('https://api.stormpath.com/v1/directories/xxx/groups', $group_data_string);
$group_href = $res->href;
```
3: Associate account with group via Account Href and Group Href
```php
$group_mem_data = array('account' => array('href' => $account_href), 'group' => array('href' => $group_href));
$group_mem_data_string = json_encode($group_mem_data);
$res = curl_post_stormpath('https://api.stormpath.com/v1/groupMemberships', $group_mem_data_string);
```
4: Store Group Membership ID for additional users	
```php
preg_match("/https:\/\/api.stormpath.com\/v1\/groupMemberships\/(.*)$/i", $res->href, $group_regex);
$group_id = $group_regex[1];
```

Now my question is, why is the ID in Stormpath for the group and the group membership ID that you get when you initially create the group two different ID's? Not to mention there doesn't look to be a short way to retrieve this group membership id for future use other than the initial group creation since it is not listed anywhere in Stormpath. In order to add new users via the API for future users into the same group, we need that group_id -- yet it is nowhere to be found on Stormpaths UI. 

When I ran through this scenario, on Stormpath the ID for the group I created is as follows.
Stormpath ID/Stormpath Rest URL: 1EdRuZvh7NyVnyMFaDokxo
API/$group_id: 1EufnhMvPMLAfuGuw7CFgY

If I'm not mistaken, previously these two were the same but somehow changed in the last month or so?

**Comment by dkvk** [comment]
Hi @asithade 

Groups and Group Memberships are two different resources. Thats why the have different IDs.
[The Group Membership is the resource that connects a Account with the Group](http://docs.stormpath.com/php/product-guide/#group-memberships)

Group resources are associated with [Directories and can be listed from there](http://docs.stormpath.com/php/product-guide/#directory-groups)

Group IDs can be found under the Details page in the admin console of Stormpaths UI
![image](https://cloud.githubusercontent.com/assets/1168561/8668701/2b44e7c0-2a0e-11e5-849d-4e91ea668929.png)

**Comment by asithade** [comment]
Thanks for that @dkvk !

Updated code to reflect this now.
