### ISSUE TITLE
Get a resource based on a href fragment

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-php#67]
For example:

client.get('/applications/3QIMlJKKN2whGCYzXXw1t8');

This should resolve to getting the object based on the baseUrl when building the client, similar to making the call to:

client.get('https://api.stormpath.com/v1/applications/3QIMlJKKN2whGCYzXXw1t8');

or 

client.get('https://enterprise.stormpath.io/v1/applications/3QIMlJKKN2whGCYzXXw1t8');

**Comment by bretterer** [comment]
@omgitstom Should this be available for each resource too?    `Stormpath\Resource\Application::get('/applications/3QIMlJKKN2whGCYzXXw1t8');`  or maybe even `Stormpath\Resource\Application::get('3QIMlJKKN2whGCYzXXw1t8');`

**Comment by bretterer** [comment]
Set to release in 1.9.0.beta
