### ISSUE TITLE
Upgrade firebase/php-jwt composer dependency to 2.2.0 or 3.0.0

### ISSUE THREAD

**Issue by Guibod** [stormpath/stormpath-sdk-php#69]
Please take note that firebase/php-jwt 2.0.0 (explicit dependency in 1.6.0beta composer.json) has known security issues.

See https://github.com/firebase/php-jwt changelog:

> 2.0.0 / 2015-04-01
> Note: It is strongly recommended that you update to > v2.0.0 to address known security vulnerabilities > in prior versions when both symmetric and asymmetric keys are used together.

**Comment by Guibod** [comment]
I've just added a pull request.

**Comment by bretterer** [comment]
Ref PR: #71

**Comment by bretterer** [comment]
Implemented in 1.7.0-beta
