### ISSUE TITLE
High memory usage on email token verification?

### ISSUE THREAD

**Issue by beck24** [stormpath/stormpath-sdk-php#75]
[03-Aug-2015 22:24:55 UTC] PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 32 bytes) in /vendor/stormpath/sdk/src/Stormpath/Util/Magic.php on line 28
    [03-Aug-2015 22:29:46 UTC] PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted (tried to allocate 72 bytes) in /vendor/stormpath/sdk/src/Stormpath/Util/Magic.php on line 28
    [03-Aug-2015 22:32:17 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in /vendor/stormpath/sdk/src/Stormpath/Resource/Resource.php on line 141
    [03-Aug-2015 22:48:44 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in /vendor/stormpath/sdk/src/Stormpath/Resource/Resource.php on line 141

Started out with 64M, bumped up to 128 and still getting OOM.
The triggering code is very simple:

    try {
	$client = get_client();
	if ($client) {
		$account = $client->tenant->verifyEmailToken($vars['sptoken']);
	}
	else {
		register_error(elgg_echo('email:confirm:fail'));
	}

    } catch (\Exception $exc) {
	register_error($exc->getMessage());
	forward();
    }

I've verified that $vars['sptoken'] is correct, and it is in fact changing the account status for them in the stormpath directory, but it's throwing OOM in the verifyEmailToken method.

**Comment by omgitstom** [comment]
Hi @beck24,

Thanks for reporting this.  What version of the Stormpath PHP SDK are you using?  Is there any other configuration information that you can provide?

Also, I'm curious about what the memory usage is before the try block, after you get the client, before you call the verifyEmailToken function and after.

You can get PHP to output this information by: http://php.net/memory_get_usage

Thanks!
Tom

cc: @bretterer

**Comment by beck24** [comment]
I was using 1.3 (apparently the sample composer.json is a little behind) - I just updated to 1.8 and it's still doing the same thing

I logged error usaged

    [03-Aug-2015 23:30:40 UTC] pre block: 20723744
    [03-Aug-2015 23:30:40 UTC] got client: 20723888
    [03-Aug-2015 23:30:40 UTC] pre validation: 20723888

There is no after validation because it's OOM by then.  It's going in only using ~18MB
I'm running this on a basic XAMPP setup on Mac, all other functions that I've tested have been working fine.  I can validate password reset tokens for example.

**Comment by beck24** [comment]
Here's the entire code that runs: https://github.com/arckinteractive/elgg_stormpath/blob/master/views/default/resources/stormpath/emailverification.php

All that happens leading up to that is the booting of the elgg engine.  I've done enough integrations in elgg to be fairly certain there's nothing there that could/should affect it.

**Comment by omgitstom** [comment]
Hi @beck24,

Just wanted to update you.  We are working on a fix and we are treating this with priority.  Stormpath will be cutting a release to fix this issue.  We expect the work to be done and release by end of the week, but if we can get it out sooner we will.

Let me know if you have any questions in the meantime.

Thanks,
Tom

**Comment by beck24** [comment]
Awesome thank you!

**Comment by bretterer** [comment]
@beck24, Again, thank you for notifying us of this bug.  We just cut a new release of the SDK to fix this issue.  Please update to at least 1.8.1.beta and your issue should be resolved.  If you need anything further, please open a new issue here or email support@stormpath.com

**Comment by beck24** [comment]
Much appreciated, checking it out now!

**Comment by beck24** [comment]
Works great, thanks :+1:

**Comment by bretterer** [comment]
@beck24 Glad to hear it.  Let us know if you see anything else, and as aways, we welcome your feedback!
