### ISSUE TITLE
Update customData object after retrieving the customData object

### ISSUE THREAD

**Issue by dadixon** [stormpath/stormpath-sdk-php#96]
I'm trying to update an array inside my customData object but nothing happens.  If I save the array directly, it works fine, but if I set my $settings variable, it breaks.

global $client;

        $account = $client->dataStore->getResource($this->href, \Stormpath\Stormpath::ACCOUNT);
        $customData = $account->customData;
//        $settings = $customData->settings;

        $module = new stdClass();
        $module->modules = $modules;

//        $settings->modules = $modules;
        $customData->settings = $module;
        $customData->save();

This works, but if I take the first comment out and run it, nothing happens.  What am I missing?

**Comment by bretterer** [comment]
@dadixon 

Could you please give me the output of the error you are getting?

If it is just not displaying anything, you can try to wrap this in a try/catch block and output the Exception object.

Brian

**Comment by dadixon** [comment]
I can't upload a txt file so here's the main error problems:

[status] => 400
                    [code] => 3003
                    [message] => Oops! We encountered an unexpected error.  Please contact support and explain what you were doing at the time this error occurred.
                    [developerMessage] => Property name 'createdAt' is invalid.  Property names may not equal any of the following reserved names: 'href', 'createdAt', 'modifiedAt', meta', 'spMeta', 'spmeta', 'ionmeta', or 'ionMeta'.
                    [moreInfo] => http://docs.stormpath.com/errors/3003

is that enough?

**Comment by dadixon** [comment]
global $client;
        try {
        $account = $client->dataStore->getResource($this->href, \Stormpath\Stormpath::ACCOUNT);
        $customData = $account->customData;
        $settings = $customData->settings;
        $module = new stdClass();
        $module->modules = $modules;
        $settings->modules = $modules;
        $customData->settings = $module;
        $customData->save();

        } catch (\Stormpath\Resource\ResourceError $re)
        {
            echo 'Message: ' . $re->getMessage();
            echo 'HTTP Status: ' . strval($re->getStatus());
            echo 'Developer Message: ' . $re->getDeveloperMessage();
            echo 'More Information: ' . $re->getMoreInfo();
            echo 'Stormpath Error Code: ' . strval($re->getErrorCode());
        }

**Comment by bretterer** [comment]
@dadixon 

Using your code above, I am not seeing any errors come though.  Could you please tell me which version of the SDK you are using so I can match my setup to yours?  I am using the latest 1.10.0.beta.

In my testing, I am assuming $modules is an array of data.

Brian

**Comment by dadixon** [comment]
I'm using composer.  I just upgraded and I'm using "stormpath/sdk": "1.3.*@beta"

**Comment by dadixon** [comment]
I upgraded to 1.6.*@beta and it works now!!!  Thanks
